_target_: src.models.coacn.COACN

data_dir: ${data_dir}
mashup_embed_path: api_mashup/embeddings/text_glove_mashup_embeddings.npy
domain_embed_path: coacn/partial_bert_domain_embeddings.npy
api_embed_path: api_mashup/embeddings/partial/text_glove_api_embeddings.npy
invoked_matrix_path: api_mashup/partial_invoked_matrix.npy
mashup_embed_channels: 300
api_embed_channels: 300
domain_embed_channels: 300
feature_dim: 128

hp_beta: 0.8
hp_num_gcn_layer: 2
hp_weight_gcn_layer: [0.5, 0.5]

lr: 0.001
weight_decay: 0.00001