_target_: src.models.mlp.MLP

data_dir: ${data_dir}/api_mashup
api_embed_path: embeddings/partial/text_bert_api_embeddings.npy
mashup_embed_channels: 300
mlp_output_channels: 300
lr: 0.001
weight_decay: 0.00001