_target_: src.datamodules.mashup_datamodule.MashupDataModule

data_dir: ${data_dir}/api_mashup
num_candidates: 21495
mashup_path: embeddings/text_glove_mashup_embeddings.npy
api_path: embeddings/total/text_glove_api_embeddings.npy
invoked_path: total_invocation.pkl
pair_in_training: true
negative_samples_ratio: 5

train_val_test_split: [3190, 912, 455] # 7: 2: 1
batch_size: 64
num_workers: 1
pin_memory: true